# Makefile para AraraLedger - Passo 1
# Compila apenas o programa de teste hello-files

COBC      = cobc
COBCFLAGS = -free -Wall

BIN_DIR   = bin
SRC_DIR   = src

.PHONY: all run-hello clean

all: $(BIN_DIR)/hello-files

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

$(BIN_DIR)/hello-files: $(SRC_DIR)/util/hello-files.cob | $(BIN_DIR)
	$(COBC) $(COBCFLAGS) -x $< -o $@

run-hello: $(BIN_DIR)/hello-files
	./$(BIN_DIR)/hello-files

clean:
	rm -f $(BIN_DIR)/*